# Generated by Django 5.0.1 on 2024-10-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalystcount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='domain',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
